# -*- coding: utf-8 -*-
"""sort_object_y.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WsmzwQEI5JNHBjhrLe95O3sxpLjUTZgk
"""

obj_detected = {'bottle': [110, 30], 'glass': [60, 35], 'book': [310, 23], 'phone': [90, 33], 'pen': [155, 100], 'mouse':  [200, 45], 'remote': [298, 165], 'fan': [300, 36]} 
y =  dict(soted(ob_detected.run(), key = lambda  run:  ject[1]))
pint(y)